[package]
name = "casync-rs"
version = "0.1.0"
authors = ["Krishna Kumar <krishnak@thoughtworks.com>"]

[dependencies]
hash-roll = "0.2.0"
clap = "2.32.0"
rust-crypto = "0.2.36"
zstd = "0.4.14"
reqwest = "0.9.4"
url = "1.7.1"